/* GENERATED by tools/build_present.mjs from app/app.js — do not edit by hand.
   Find My Car result composition as a pure module: every block between "verbatim" markers is copied character-for-character
   from the released app/app.js (which is not modified), so the server transport and the browser say the same thing.
   No DOM, window, storage or network here. Drift guard: node tools/build_present.mjs --check */
(function (root) {
  'use strict';

  // b64 for share tokens: the browser's btoa where present, Node's Buffer otherwise (same output for the latin-1 input enc() builds)
  const btoa = typeof root.btoa === 'function' ? s => root.btoa(s) : s => Buffer.from(s, 'latin1').toString('base64');
  const atob = typeof root.atob === 'function' ? s => root.atob(s) : s => Buffer.from(s, 'base64').toString('latin1');

  // one presenter per (dataset, engine, copy); setLang() switches the engine-owned copy (I.S.en / I.S.ar)
  function create(U, E, I) {
    const byId = {}; U.models.forEach(m => { byId[m.id] = m; });
    let lang = 'en', S = I.S.en;
    const setLang = l => { if (!I.S[l]) throw new Error('unsupported locale: ' + l); lang = l; S = I.S[l]; };

    // ---- verbatim: helpers ----
  const esc = s => String(s == null ? '' : s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  const fmt = n => Number(n).toLocaleString('en-US');
  const num = n => `<span class="num">${fmt(n)}</span>`;
  const money = n => `<span class="money">${S.egp(num(Math.round(n)))}</span>`;
  const millTxt = n => { const v = n / 1e6; return (Math.round(v * 100) / 100).toString(); };
  const mill = n => `<span class="money">${S.mill(`<span class="num">${millTxt(n)}</span>`)}</span>`;
  const nm = id => { const m = byId[id]; return m ? `<span class="ltr">${esc(m.brand)} ${esc(m.model)}</span>` : ''; };
  const nmShort = id => { const m = byId[id]; return m ? `<span class="ltr">${esc(m.model)}</span>` : ''; };
  const lat = s => `<span class="ltr">${esc(s)}</span>`;
  const enc = o => btoa(unescape(encodeURIComponent(JSON.stringify(o)))).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
  const dec = s => JSON.parse(decodeURIComponent(escape(atob(s.replace(/-/g, '+').replace(/_/g, '/')))));
  const SHARE_KEYS = ['drive4', 'offroad', 'sizePref', 'brandsOnly', 'ptNo', 'budget', 'budgetMin', 'budgetMode', 'stretch', 'budgetFrom', 'body', 'bodyAny', 'bodyImplied', 'notBody', 'seats', 'who', 'usage', 'pt', 'chinese', 'priorities', 'checks',
    'brandsPrefer', 'brandsExclude', 'shortlist', 'reference', 'aspiration', 'attraction', 'avoid'];
  const slim = b => { const o = {}; SHARE_KEYS.forEach(k => { const v = b[k]; if (v != null && v !== false && !(Array.isArray(v) && !v.length)) o[k] = v; }); return o; };

    // ---- verbatim: brief helpers + follow-up selection ----
  const norm = b => E.normalizeBrief(b, byId);
  // re-derive shortlist/aspiration after a budget change ("GLC" becomes reachable or not)
  function renorm(b) {
    const x = { ...b };
    x.mentions = [...(x.shortlist || []), ...(x.aspiration || [])].map(id => ({ id, role: 'consider' }))
      .concat((x.reference || []).map(id => ({ id, role: 'reference' })));
    x.shortlist = []; x.aspiration = []; x.reference = [];
    if (x.bodyImplied) { delete x.body; delete x.bodyImplied; }
    return norm(x);
  }
  function merge(b, p) {
    const o = { ...b };
    for (const [k, v] of Object.entries(p)) {
      if (k === 'text' || k === 'extracted' || v == null) continue;
      if (Array.isArray(v)) o[k] = [...new Set([...(o[k] || []), ...(k === 'mentions' ? [] : v)])];
      else o[k] = v;
    }
    if (p.mentions) o.mentions = [...(o.mentions || []), ...p.mentions.filter(x => !(o.mentions || []).some(y => y.id === x.id))];
    return o;
  }
  const family = b => (b.who || []).some(w => ['kids', 'family', 'parents'].includes(w));

  const FOLLOW_UPS = ['drive', 'size', 'pt', 'chinese', 'usage', 'priorities'];
  function nextQ(brief, asked, path) {
    const nb = norm(brief);
    const derived = nb.budgetFrom && nb.budgetFrom !== 'shortlist';
    if (!asked.includes('budget') && !brief.budget && !derived) return 'budget';
    if ((nb.aspiration || []).length && !nb.attraction && !asked.includes('attraction')) return 'attraction';
    if (!(nb.body && nb.body.length) && !nb.bodyAny && nb.seats !== 7 && !asked.includes('body')) return 'body';
    const bodyAllows7 = !(nb.body && nb.body.length) || nb.body.some(x => x === 'suv' || x === 'mpv');
    if (nb.seats == null && !asked.includes('seats') && bodyAllows7 && (path === 'guided' || family(nb)) && E.material(U, nb, [{ seats: null }, { seats: 7 }])) return 'seats';
    // then only the follow-up that best separates the cars still tied on this brief (at most 4)
    // stated off-road intent: whether four-wheel drive is a must decides eligibility, so it comes first
    if (nb.offroad && nb.drive4 == null && !asked.includes('drive')) return 'drive';
    const follow = asked.filter(x => FOLLOW_UPS.includes(x)).length;
    if (follow < 4) { const q = E.nextQuestion(U, nb, asked); if (q) return q; }
    if (!asked.includes('more')) return 'more';
    return null;
  }

    // ---- verbatim: "Here's what we understood" ----
  const joinList = a => a.join(lang === 'ar' ? '، ' : ', ');
  function summaryRows(b) {
    const R = [];
    const add = (key, value) => { if (value) R.push({ key, label: S.s_rows[key], value }); };
    if (b.budget) {
      const from = b.budgetFrom === 'shortlist' ? S.s_budget_from_sl : b.budgetFrom && byId[b.budgetFrom] ? S.s_budget_from(nm(b.budgetFrom)) : '';
      const val = b.budgetMode === 'range' && b.budgetMin ? S.s_range(mill(b.budgetMin), mill(b.budget)) : mill(b.budget);
      add('budget', S.s_budget(val, b.budgetMode, b.stretch, from));
    }
    if (b.body && b.body.length) add('body', joinList(b.body.map(x => S.body[x])) + (b.bodyImplied ? ` <span class="muted">(${S.s_body_implied})</span>` : ''));
    else if (b.bodyAny) add('body', S.s_any);
    if (b.seats) add('seats', S.s_seats[b.seats]);
    if (b.sizePref) add('size', S.size_v[b.sizePref]);
    if (b.drive4 === true) add('drive', S.drive_v);
    if (b.offroad) add('offroad', S.offroad_v);
    if ((b.who || []).length) add('who', joinList(b.who.map(w => S.who[w])));
    if (b.usage) add('usage', S.usage_v[b.usage]);
    if (b.pt) add('pt', S.pt_v[b.pt]);
    if (b.chinese) add('chinese', S.chinese_v[b.chinese]);
    if ((b.shortlist || []).length) add('shortlist', joinList(b.shortlist.map(nm)));
    if ((b.reference || []).length) add('reference', joinList(b.reference.map(nm)));
    if ((b.aspiration || []).length) add('aspiration', joinList(b.aspiration.map(nm)) + (b.attraction ? ` — ${S.attr_v[b.attraction]}` : ''));
    if ((b.brandsOnly || []).length) add('only', joinList(b.brandsOnly.map(brandName)));
    if ((b.brandsPrefer || []).length) add('brands', joinList(b.brandsPrefer.map(brandName)));
    if ((b.ptNo || []).length) add('pt_no', joinList(b.ptNo.map(x => S.pt[x])));
    const avoid = [...(b.brandsExclude || []).map(brandName), ...(b.avoid || []).map(nm)];
    if (avoid.length) add('avoid', joinList(avoid));
    if ((b.priorities || []).length) add('priorities', joinList(b.priorities.map(p => S.prio_v[p])));
    if ((b.checks || []).length) add('checks', joinList(b.checks.map(p => S.prio_v[p])));
    if (b.notes) add('notes', `<span dir="auto">“${esc(b.notes)}”</span>`);
    // comparative brand phrases the brief cannot represent: shown verbatim, never applied (see brief.js FLOOR_*)
    if ((b.unresolved || []).length) add('unresolved', `${b.unresolved.map(u => `<span dir="auto">“${esc(u.text)}”</span>`).join(' · ')} <span class="muted">— ${S.unresolved_hint}</span>`);
    return R;
  }
  function brandName(bid) { const m = U.models.find(x => x.brand_id === bid); return m ? lat(m.brand) : esc(bid); }

    // ---- verbatim: result pieces (WHY, trade-offs, specs, versions, market, next steps, what could change) ----
  function warrantyTxt(m) {
    // shown only when it comes from the official distributor; price-site warranty claims are not verified
    if (!m.warranty_years || !m.warranty_verified) return null;
    const raw = (m.warranty || []).join(' ');
    const km = raw.match(/(\d{1,3}(?:,\d{3})+|\d{5,6})\s*km/i);
    return S.warranty_v(`<span class="num">${m.warranty_years}</span>`, km ? num(+km[1].replace(/,/g, '')) : null);
  }
  const pts = trims => { const s = new Set(); trims.forEach(t => s.add(t.plugin ? 'plugin' : t.pt)); return [...s].filter(Boolean); };

  function reasons(p, r) {
    const m = byId[p.id], b = r.brief, B = r.terr.budget, out = [];
    const lo = p.fit[0].min, hi = p.fit[p.fit.length - 1].min;
    if (p.stretch) out.push(S.why.stretch({ range: S.from_to(money(lo), money(hi)), amount: money(p.stretch.over), buys: joinList(p.stretch.buys.map(k => S.fk[k] || k)), vs: nm(p.stretch.vs) }));
    else if (hi > B && lo > B) out.push(S.why.budget_over({ range: S.from_to(money(lo), money(hi)), amount: money(lo - B) }));
    else if (hi < B * 0.9) out.push(S.why.budget_under({ range: S.from_to(money(lo), money(hi)), amount: money(B - hi) }));
    else out.push(S.why.budget_in({ range: S.from_to(money(lo), money(hi)), n: p.fit.length }));
    if (b.seats === 7 && p.seven) out.push(S.why.seven({ family: family(b) || (b.who || []).includes('wife') }));
    if (p.ref && p.ref.kind && p.ref.diff === 0) out.push(S.why.ref_same({ ref: nm(p.ref.ids[0]) }));
    if (p.ref && p.ref.diff > 0 && ((b.priorities || []).includes('space') || b.seats === 7)) out.push(S.why.ref_bigger({ ref: nm(p.ref.ids[0]) }));
    const pr = b.priorities || [], parts = p.parts || {};
    if (pr.includes('space') && parts.space >= 0.6 && p.sizeKey) out.push(S.why.space({ size: S.size(p.sizeKey) }));
    if (pr.includes('easy') && parts.easy >= 0.6 && p.sizeKey) out.push(S.why.easy({ size: S.size(p.sizeKey) }));
    if (b.sizePref && parts.sizePref >= 0.75 && p.sizeKey) out.push(S.why.size_pref({ size: S.size(p.sizeKey) }));
    if (pr.includes('premium') && p.premium && p.sizeKey) out.push(S.why.premium({ size: S.size(p.sizeKey) }));
    if (b.drive4 && m.awd) out.push(S.why.awd());
    if (pr.includes('pocket') && p.entry < B) out.push(S.why.pocket({ entry: money(p.entry), amount: money(B - p.entry) }));
    if (pr.includes('popular') && m.reg && m.reg.rank_in_body_last12) out.push(S.why.popular({ rank: num(m.reg.rank_in_body_last12), of: num(m.reg.of_body), body: S.body_pl[m.body] }));
    if ((b.pt === 'hybrid' || pr.includes('economy') || b.usage === 'city') && p.hybrid) out.push(S.why.hybrid());
    else if (b.usage === 'city' && p.anyEv && b.pt === 'open') out.push(S.why.ev_city());
    if ((b.brandsPrefer || []).includes(m.brand_id)) out.push(S.why.brand({ brand: lat(m.brand) }));
    const asp = (b.aspiration || []).map(id => byId[id]).filter(Boolean);
    if (asp.length && b.attraction) {
      const a = asp[0];
      if (b.attraction === 'brand' && a.brand_id === m.brand_id) out.push(S.why.attr_brand({ brand: lat(m.brand), asp: nm(a.id) }));
      else if (b.attraction === 'brand' && a.origin === m.origin) out.push(S.why.attr_origin({ origin: S.origin(m.origin), asp: nm(a.id) }));
      else if (b.attraction === 'premium' && p.premium) out.push(S.why.attr_premium({ asp: nm(a.id) }));
      else if (b.attraction === 'performance' && p.hp) out.push(S.why.attr_perf({ hp: num(p.hp) }));
      else if (b.attraction === 'size' && p.ref && p.ref.diff >= 0 && p.sizeKey) out.push(S.why.space({ size: S.size(p.sizeKey) }));
    }
    return [...new Set(out)].slice(0, 5);
  }

  function trades(p, r) {
    const m = byId[p.id], b = r.brief, B = r.terr.budget, out = [];
    const higher = p.all.find(t => t.min > p.pick.min);
    if (p.fit.length === 1 && higher) out.push(S.trade.entry_only({ trim: lat(p.pick.label), price: money(higher.min) }));
    if (b.usage === 'city' && p.petrolOnly) out.push(S.trade.petrol_city());
    if (p.ev && b.usage === 'long') out.push(S.trade.ev_long());
    else if (p.ev && b.pt !== 'open' && b.pt !== 'ev') out.push(S.trade.ev_charge());
    if (p.ref && p.ref.diff < 0) out.push(S.trade.ref_smaller({ ref: nm(p.ref.ids[0]) }));
    if (p.ref && p.ref.diff > 0 && !((b.priorities || []).includes('space') || b.seats === 7)) out.push(S.trade.ref_bigger({ ref: nm(p.ref.ids[0]) }));
    if (m.reg && m.reg.trend === 'new') out.push(S.trade.new_model({ month: S.month(m.reg.first_month) }));
    else if (!m.reg || (m.reg.last12 || 0) < 100) out.push(S.trade.low_presence({ n: num((m.reg && m.reg.last12) || 0) }));
    if (family(b) && b.seats !== 7 && m.seats && Math.max(...m.seats) <= 5) out.push(S.trade.not_seven_family());
    return out.slice(0, 4);
  }

  function imageBlock(m, cls) {
    if (!m.image) return '';
    return `<figure class="${cls}"><img src="${esc(m.image.src)}" alt="${esc(m.brand + ' ' + m.model)}" loading="lazy" referrerpolicy="no-referrer" onerror="this.closest('figure').remove()">
      <figcaption><a href="${esc(m.image.page)}" target="_blank" rel="noopener">${esc(S.photo(m.image.credit))}</a></figcaption></figure>`;
  }

  function specs(p) {
    const m = byId[p.id], rows = [];
    if (p.sizeKey) rows.push([S.sp.size, S.size(p.sizeKey)]);
    if (m.seats) rows.push([S.sp.seats, m.seats.map(num).join(' / ')]);
    const pt = pts(p.fit.length ? p.fit : p.all);
    if (pt.length) rows.push([S.sp.pt, joinList(pt.map(x => S.pt[x]))]);
    if (m.hp && m.hp.length) rows.push([S.sp.hp, S.hp(num(Math.max(...m.hp)))]);
    const w = warrantyTxt(m); if (w) rows.push([S.sp.warranty, w]);
    if (m.model_year) rows.push([S.sp.year, `<span class="num">${m.model_year}</span>`]);
    if (m.distributor) rows.push([S.sp.distributor, lat(m.distributor)]);
    return `<dl class="specs">${rows.map(([k, v]) => `<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl>`;
  }

  function versionsBlock(p, r) {
    const above = p.all.filter(t => t.min > r.terr.ceil);
    return `<ul class="vers">${p.fit.map(t => `<li class="${t === p.pick || (t.label === p.pick.label && t.min === p.pick.min) ? 'pick' : ''}"><span class="ltr">${esc(t.label)}</span><span>${money(t.min)}${t.official ? ` <span class="chip ok tiny">${S.official}</span>` : ''}</span></li>`).join('')}</ul>
      ${above.length ? `<p class="muted small">${S.above_range(money(Math.min(...above.map(t => t.min))))}</p>` : ''}`;
  }

  function marketBlock(m) {
    const g = m.reg;
    if (!g || !g.since_2021) return '';
    const tags = [];
    if (g.rank_in_body_last12 && g.rank_in_body_last12 <= 10) tags.push(S.mk.popular({ rank: num(g.rank_in_body_last12), of: num(g.of_body), body: S.body_pl[m.body] }));
    const years = Object.keys(g.yearly || {}).sort();
    if (years.length >= 5 && years[0] === '2021' && years.every(y => g.yearly[y] > 0)) tags.push(S.mk.consistent);
    if (g.trend === 'new') tags.push(S.mk.new({ month: S.month(g.first_month) }));
    else if (g.trend && S.mk[g.trend] && typeof S.mk[g.trend] === 'string') tags.push(S.mk[g.trend]);
    const max = Math.max(1, ...years.map(y => g.yearly[y]));
    const bars = years.map(y => `<div class="yb" title="${y}: ${fmt(g.yearly[y])}"><i style="height:${Math.max(2, Math.round(g.yearly[y] / max * 56))}px"></i><span class="num">${y === '2026' ? S.mk_year_partial(y) : y}</span><span class="num v">${fmt(g.yearly[y])}</span></div>`).join('');
    return `<div class="market">${tags.length ? `<div class="chips">${tags.map(t => `<span class="chip">${t}</span>`).join('')}</div>` : ''}
      <p class="small">${S.mk_line({ last12: num(g.last12 || 0), total: num(g.since_2021) })}</p>
      <div class="years" dir="ltr">${bars}</div></div>`;
  }

  function nextSteps(p) {
    const m = byId[p.id];
    const off = p.fit.find(t => t.official);
    return `<p class="small">${off && m.distributor ? S.next_official({ d: lat(m.distributor), date: S.month(off.date.slice(0, 7)) }) : S.next_generic}</p>`;
  }

  // the main pick's lead is not robust (confidence 'lean'): say what it rests on
  const isLean = (p, r) => !!(r.hero && p.id === r.hero.id && !r.equal && !r.heroFromShortlist && r.confidence && r.confidence.level === 'lean');
  function changeBlock(r) {
    const c = r.confidence, items = c.depends.map(k => S.dep[k]).filter(Boolean);
    // name the runner-up only when it is on screen (it can sit in a tied group the alternatives sample)
    if (c.vs && r.alts.some(a => a.id === c.vs)) items.push(S.dep_alt({ n: nm(c.vs) }));
    return items.length ? `<div><h3>${S.change_h}</h3><ul class="list">${items.map(x => `<li><span>${x}</span></li>`).join('')}</ul></div>` : '';
  }

  function detail(p, r, dark) {
    const why = reasons(p, r), tr = trades(p, r), lean = isLean(p, r);
    const mk = dark ? 'mk' : 'mk light';
    return `
      <div class="cols">
        <div><h3>${lean ? S.why_h_lean : S.why_h}</h3><ul class="list">${why.map(x => `<li><span class="${mk} good" aria-hidden="true">✓</span><span>${x}</span></li>`).join('')}</ul></div>
        ${tr.length ? `<div><h3>${S.trade_h}</h3><ul class="list">${tr.map(x => `<li><span class="${mk} bad" aria-hidden="true">!</span><span>${x}</span></li>`).join('')}</ul></div>` : ''}
      </div>
      ${lean ? `<div class="cols">${changeBlock(r)}</div>` : ''}
      <div class="cols">
        <div><h3>${S.versions_h}</h3>${versionsBlock(p, r)}</div>
        <div><h3>${S.specs_h}</h3>${specs(p)}</div>
      </div>
      ${marketBlock(byId[p.id]) ? `<div><h3>${S.market_h}</h3>${marketBlock(byId[p.id])}</div>` : ''}
      <div><h3>${S.next_h}</h3>${nextSteps(p)}</div>`;
  }

  function vsLine(p, hero) {
    const H = nm(hero.id);
    return (p.vs || []).slice(0, 3).map(d => S.vs[d.k]({ hero: H, amount: money(d.v || 0), a: num(d.a || 0), h: num(d.h || 0) }));
  }


    // ---- verbatim (renderResult): notices above the result ----
    function topCardsOf(r, b) {
    const topCards = [];
    // aspiration
    if (r.aspiration) {
      for (const a of r.aspiration) {
        if (!a.entry) continue;
        const cb = a.cheapestBrand && a.cheapestBrand.id !== a.id && a.cheapestBrand.p > r.terr.ceil ? `<p>${S.asp_brand({ brand: lat(byId[a.id].brand), n: nm(a.cheapestBrand.id), price: money(a.cheapestBrand.p) })}</p>` : '';
        topCards.push(`<section class="note-card"><h3>${S.asp_h(nm(a.id))}</h3><p>${S.asp_line({ n: nm(a.id), entry: money(a.entry), times: num(a.times), budget: mill(r.terr.budget) })}</p>${cb}
          ${b.attraction === 'premium' && r.hero && ![r.hero, ...r.alts].some(x => x.premium) ? `<p>${S.asp_no_premium({ budget: mill(r.terr.budget) })}</p>` : b.attraction ? `<p>${S.asp_attr({ what: S.attr_v[b.attraction] })}</p>` : ''}</section>`);
        break;
      }
    }
    if (r.shortlist && r.shortlist.allOut) {
      const cars = joinList(r.shortlist.rows.map(x => nm(x.id)));
      const k = r.shortlist.allOut[0];
      topCards.push(`<section class="note-card conflict"><h3>${S.conflict_h}</h3><p>${(S.conflict[k] || S.conflict.other)({ cars })}</p>
        ${S.relax_key[k] ? `<button class="btn btn-ghost" type="button" data-relax="${k}">${S.conflict_relax({ cars })}</button>` : ''}</section>`);
    } else if (r.shortlist) topCards.push(shortlistCard(r));
    if (b.offroad) topCards.push(`<div class="notice"><span class="ic" aria-hidden="true">i</span><p>${b.drive4 ? S.offroad_note_4wd : S.offroad_note}</p></div>`);
    (r.unmet || []).forEach(u => topCards.push(`<div class="notice"><span class="ic" aria-hidden="true">i</span><p>${S.unmet[u.key]({ n: u.nearest ? nm(u.nearest.id) : '', price: u.nearest ? money(u.nearest.p) : '' })}</p></div>`));
    if (r.equal) topCards.push(`<div class="notice"><span class="ic" aria-hidden="true">i</span><p>${S.equal_note({ n: num(r.tier), shown: num(1 + r.alts.length) })}</p></div>`);
    if (r.widened) topCards.push(`<div class="notice"><span class="ic" aria-hidden="true">i</span><p>${S.widened}</p></div>`);
      return topCards;
    }
    // ---- verbatim (renderResult): checks before buying ----
    function checksOf(b) {
    const checks = [...new Set([...(b.checks || []).filter(c => S.check[c]), 'test', 'terms'])];
      return checks;
    }
    // ---- verbatim (renderResult): template expressions ----
    const nearestHtml = r => `${r.nearestAbove ? `<section class="nomatch"><h2>${S.nearest_h}</h2><ul class="vs">${r.nearestAbove.map(x => `<li>${S.nearest_line({ n: nm(x.id), price: money(x.price), amount: money(x.over) })}</li>`).join('')}</ul></section>` : ''}`;
    const nomatchHeadHtml = r => `${r.nearestAbove ? '' : `<h2>${S.nomatch_h}</h2>`}<p>${S.nomatch_p}</p>`;
    const fixesHtml = fixes => `${fixes.map(f => `<button class="btn btn-ghost" type="button" data-fix="${f.key}" data-to="${f.to || ''}">${f.key === 'budget' ? S.fix.budget(mill(f.to)) : S.fix[f.key](num(f.n))}</button>`).join('')}`;
    const eyebrowOf = r => `${r.heroFromShortlist ? S.eyebrow_hero_yours : r.confidence && r.confidence.level === 'lean' ? S.eyebrow_lean : S.eyebrow_clear}`;
    const heroSizeOf = h => `${h.sizeKey ? S.size(h.sizeKey) : ''}`;
    const heroRangeOf = h => `${S.from_to(money(h.fit[0].min), money(h.fit[h.fit.length - 1].min))}`;
    const heroSubOf = h => `${h.stretch ? S.over_by(money(h.stretch.over)) : S.n_versions(num(h.fit.length))}`;
    const lessHtml = (r, b) => `${S.less_line({ n: nm(r.less.id), price: money(r.less.price), saves: money(r.less.saves), seven: r.less.seven && b.seats === 7, same: r.less.sameSize })}`;
    const checkItemsHtml = checks => `${checks.map(c => `<li>${S.check[c]}</li>`).join('')}`;

    // ---- verbatim: shortlist verdict, alternative card, compare table ----
  function shortlistCard(r) {
    const s = r.shortlist, lines = [];
    if (s.winner && s.second) {
      const a = nm(s.winner), bb = nm(s.second);
      lines.push(`<p class="verdict">${s.tie ? S.sl_tie({ a, b: bb }) : s.close ? S.sl_close({ a, b: bb, edge: S.sl_edge[s.edge] || S.sl_edge.budget }) : S.sl_win({ a, b: bb })}</p>`);
      if (!s.close && s.diffs.length) lines.push(`<ul class="vs">${s.diffs.slice(0, 3).map(d => `<li>${S.vs[d.k]({ hero: bb, amount: money(d.v || 0), a: num(d.a || 0), h: num(d.h || 0) })}</li>`).join('')}</ul>`);
      lines.push(`<ul class="vs">${s.picks.map(p => `<li>${nm(p.id)}: ${S.sl_budget_line({ trim: lat(p.trim), price: money(p.price) })}</li>`).join('')}</ul>`);
    } else if (s.winner) lines.push(`<p class="verdict">${S.sl_one({ a: nm(s.winner) })}</p>`);
    s.rows.filter(x => !x.ok).forEach(x => lines.push(`<p>${(S.sl_out[x.why] || S.sl_out[String(x.why).replace('unknown_', '')] || S.sl_out.not_on_sale)({ n: nm(x.id), entry: x.entry ? money(x.entry) : '' })}</p>`));
    const ch = r.alts.find(x => x.role === 'challenger');
    if (ch && r.heroFromShortlist) {
      const good = ['bigger', 'more_hp', 'longer_warranty', 'cheaper', 'seven', 'hybrid'];
      const pros = (ch.vs || []).filter(d => good.includes(d.k));
      const own = reasons(ch, r).slice(1, 2)[0];
      const why = pros.length ? joinList(pros.slice(0, 3).map(d => S.vs[d.k]({ hero: nm(r.hero.id), amount: money(d.v || 0), a: num(d.a || 0), h: num(d.h || 0) }))) + '.' : (own || S.sl_also_fit);
      lines.push(`<p>${S.sl_also({ n: nm(ch.id), why })}</p>`);
    }
    return `<section class="note-card verdict-card"><h3>${S.sl_h}</h3>${lines.join('')}</section>`;
  }

  function altCard(a, h, r) {
    const m = byId[a.id];
    // equal options are not described relative to one of them
    const why = reasons(a, r).slice(0, 2), vs = a.role === 'equal' ? [] : vsLine(a, h);
    return `<article class="alt">
      ${imageBlock(m, 'alt-img')}
      <span class="chip role">${S.role[a.role] || S.role.runner_up}</span>
      <h3>${nm(a.id)}</h3>
      <p class="muted small">${a.sizeKey ? S.size(a.sizeKey) : ''}</p>
      <p class="alt-price">${S.from_to(money(a.fit[0].min), money(a.fit[a.fit.length - 1].min))}</p>
      <ul class="vs">${why.map(x => `<li>${x}</li>`).join('')}</ul>
      ${vs.length ? `<ul class="vs muted">${vs.map(x => `<li>${x}</li>`).join('')}</ul>` : ''}
      <div class="foot"><button class="btn btn-ghost" type="button" data-detail="${a.id}">${S.details}</button></div>
    </article>`;
  }

  function compareTable(list, r) {
    const lead = i => (i || r.equal ? '' : 'is-hero');
    const row = (label, f) => `<tr><th scope="row">${label}</th>${list.map((p, i) => `<td class="${lead(i)}">${f(p) || '—'}</td>`).join('')}</tr>`;
    return `<div class="table-wrap"><table class="cmp"><thead><tr><th></th>${list.map((p, i) => `<th class="${lead(i)}" scope="col">${nm(p.id)}</th>`).join('')}</tr></thead><tbody>
      ${row(S.in_range, p => S.from_to(money(p.fit[0].min), money(p.fit[p.fit.length - 1].min)))}
      ${row(S.sp.size, p => (p.sizeKey ? S.size(p.sizeKey) : ''))}
      ${row(S.sp.seats, p => { const m = byId[p.id]; return m.seats ? m.seats.map(num).join(' / ') : ''; })}
      ${row(S.sp.pt, p => joinList(pts(p.fit).map(x => S.pt[x])))}
      ${row(S.sp.hp, p => (p.hp ? S.hp(num(p.hp)) : ''))}
      ${row(S.sp.warranty, p => warrantyTxt(byId[p.id]))}
      ${row(S.market_h, p => { const g = byId[p.id].reg; return g ? S.mk_line({ last12: num(g.last12 || 0), total: num(g.since_2021 || 0) }) : ''; })}
    </tbody></table></div>`;
  }

    // ---- verbatim: the "spend less" car ranked alone against the same brief ----
  function packFor(id, r) {
    const b = { ...r.brief, budget: Math.max(...E.currentTrims(byId[id]).map(t => t.min)), budgetMode: 'around', shortlist: [], aspiration: [], reference: r.brief.reference };
    const x = E.recommend({ meta: U.meta, models: [byId[id], ...U.models.filter(mm => (r.brief.reference || []).includes(mm.id) && mm.id !== id)] }, b);
    const p = x.hero && x.hero.id === id ? x.hero : x.alts.find(a => a.id === id);
    return p || { id, pick: E.currentTrims(byId[id])[0], price: r.less.price, fit: E.currentTrims(byId[id]), all: E.currentTrims(byId[id]), parts: {}, vs: [] };
  }

    return {
      setLang, get lang() { return lang; }, get S() { return S; }, byId,
      esc, fmt, num, money, millTxt, mill, nm, nmShort, lat, enc, dec, SHARE_KEYS, slim,
      norm, renorm, merge, family, nextQ, joinList, summaryRows, brandName,
      warrantyTxt, pts, reasons, trades, imageBlock, specs, versionsBlock, marketBlock, nextSteps, isLean, changeBlock, detail, vsLine,
      topCardsOf, checksOf, nearestHtml, nomatchHeadHtml, fixesHtml, eyebrowOf, heroSizeOf, heroRangeOf, heroSubOf, lessHtml, checkItemsHtml,
      shortlistCard, altCard, compareTable, packFor,
    };
  }

  const api = { create };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  else root.CIPresent = api;
})(typeof window !== 'undefined' ? window : globalThis);
