#!/usr/bin/env node
/* Vendors P1-owned recommendation code VERBATIM for server-side execution only.
   P5 never edits these files. Upgrading = re-run with a new P1 commit, then P1 signs off.
   Usage: node scripts/vendor-p1.mjs <path-to-carindex-buyer-test checkout> <commit-sha> */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const [root, commit] = process.argv.slice(2);
if (!root || !/^[0-9a-f]{40}$/.test(commit || '')) { console.error('usage: vendor-p1.mjs <checkout> <40-char commit>'); process.exit(1); }
const FILES = ['app/engine.js', 'app/brief.js', 'app/i18n.js', 'app/redact.js'];
const manifest = { owner: 'P1', source_repo: 'KingMega1/carindex-buyer-test', source_commit: commit, files: {} };
const sources = {};
for (const f of FILES) {
  const code = readFileSync(join(root, f), 'utf8');
  const name = f.split('/').pop();
  manifest.files[name] = { path: f, sha256: createHash('sha256').update(code).digest('hex'), bytes: Buffer.byteLength(code) };
  sources[name] = code;
}
const OUT = 'src/server/p1/vendor';
writeFileSync(join(OUT, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
writeFileSync(join(OUT, 'sources.generated.ts'),
  '/* GENERATED by scripts/vendor-p1.mjs — verbatim P1 source, do not edit. Verified against manifest.json at load. */\n' +
  'export const P1_SOURCES: Record<string, string> = ' + JSON.stringify(sources) + ';\n');
console.log('vendored', Object.entries(manifest.files).map(([k, v]) => `${k} ${v.sha256.slice(0, 12)}`).join(', '));
